channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==5.9.6
  - scikit-learn==1.3.1
  - scipy==1.11.3
name: mlflow-env
