channels:
- conda-forge
dependencies:
- python=3.9.20
- pip<=24.2
- pip:
  - mlflow==2.5.0
  - cloudpickle==2.2.1
  - numpy==1.23.5
  - scikit-learn==1.3.1
  - scipy==1.13.1
name: mlflow-env
