name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Vérification du code source
      - name: Check out code
        uses: actions/checkout@v2

      # Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Mise en cache des dépendances Python
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --force-reinstall numpy

      - name: Check installed packages
        run: pip list

      # Exécution des tests unitaires
      - name: Run unit tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
